dependencies:
  color_tft:
    url: github.com/toitware/toit-color-tft
    version: ^1.1.0
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.2.0
  pixel_strip:
    url: github.com/toitware/toit-pixel-strip
    version: ^0.0.4
