name: fw_keyboard
description: A library to enable use of the Keyboard FeatherWing Rev 2.
dependencies:
  color_tft:
    url: github.com/toitware/toit-color-tft
    version: ^1.3.0
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.6.0
  pixel_strip:
    url: github.com/toitware/toit-pixel-strip
    version: ^0.2.0
