name: fw_keyboard
description: A library to enable use of the Keyboard FeatherWing Rev 2.
dependencies:
  color_tft:
    url: github.com/toitware/toit-color-tft
    version: ^2.1.0
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^2.9.0
