dependencies:
  color_tft:
    url: github.com/toitware/toit-color-tft
    version: ^1.1.0
  fw_keyboard:
    path: ..
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.2.0
