dependencies:
  color_tft:
    url: github.com/toitware/toit-color-tft
    version: ^1.3.0
  font_x11_adobe:
    url: github.com/toitlang/pkg-font-x11-adobe
    version: ^0.1.0
  fw_keyboard:
    path: ..
  pid:
    url: github.com/andersjohnsen/pid
    version: ^1.0.1
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.6.0
  pixel_strip:
    url: github.com/toitware/toit-pixel-strip
    version: ^0.2.0
  solar_position:
    url: github.com/toitware/toit-solar-position
    version: ^0.0.3
