dependencies:
  bbq10keyboard:
    path: ..
  color_tft:
    url: github.com/toitware/toit-color-tft
    version: ^1.0.0
  events:
    path: ..
  fw_keyboard:
    path: ..
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.1.0
  roboto:
    url: github.com/toitware/toit-font-google-100dpi-roboto
    version: ^1.1.0
